version: '3'
services:

  microsocnet-back:
    container_name: microsocnet-back
    image: "microsocnet-back"
    build:
      context: ./docker
    environment:
      XDEBUG_CONFIG: "client_host=${XDEBUG_HOST} client_port=${XDEBUG_PORT} idekey=${XDEBUG_IDEKEY}"
    networks:
      - microsocnet
    volumes:
      - ./:/var/www/
      - ./docker/runtime/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      host.docker.internal: host-gateway

  microsocnet-front:
    image: node:current-alpine
    user: ${UID}:${UID}
    working_dir: /home/node/app
    volumes:
    - ./public:/home/node/app
    environment:
      NODE_ENV: development
    command: "npm run serve"

  microsocnet-database:
    container_name: microsocnet-database
    networks:
      - microsocnet
    image: 'postgres:15'
    volumes:
      - microsocnet-database:/var/lib/postgresql
    environment:
        PGPASSWORD: '${DB_PASSWORD:-secret}'
        POSTGRES_DB: '${DB_DATABASE}'
        POSTGRES_USER: '${DB_USERNAME}'
        POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    ports:
      - 54321:5432

  microsocnet-minio:
    container_name: microsocnet-minio
    image: 'bitnami/minio:2022.7.26-debian-11-r2'
    ports:
      - '9105:9000'
      - '9106:9001'
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - MINIO_DEFAULT_BUCKETS=${AWS_BUCKET}
    networks:
      - microsocnet

  microsocnet-meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    volumes:
      - 'microsocnet-meilisearch:/meili_data'
    networks: 
      - microsocnet

  microsocnet-redis:
    container_name: microsocnet-redis
    networks:
      - microsocnet
    image: redis:latest
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'

volumes:
  microsocnet-database:
  microsocnet-meilisearch:

networks:
  microsocnet:
    driver: bridge    
